// Registry tool in silico — katalog referensi (fungsi, tahap, lisensi, tautan, tips).
import type { ToolLicense } from "@/types/database";

export interface ToolDef {
  name: string;
  category: string;
  description: string;
  stages: string[];
  url: string;
  license: ToolLicense;
  tips: string;
}

export const TOOLS_REGISTRY: ToolDef[] = [
  {
    name: "AutoDock Vina",
    category: "Docking",
    description: "Program docking molekuler open-source yang cepat dan populer.",
    stages: ["Docking", "Virtual Screening", "Validasi"],
    url: "https://vina.scripps.edu/",
    license: "free",
    tips: "Validasi protokol dengan redocking (RMSD < 2 Å) sebelum docking senyawa uji. Catat exhaustiveness & seed.",
  },
  {
    name: "AutoDockTools (MGLTools)",
    category: "Preparasi",
    description: "GUI untuk preparasi reseptor/ligan & pembuatan grid box.",
    stages: ["Preparasi"],
    url: "https://ccsb.scripps.edu/mgltools/",
    license: "free",
    tips: "Simpan koordinat & ukuran grid box agar reprodusibel.",
  },
  {
    name: "PyRx",
    category: "Docking",
    description: "Antarmuka virtual screening yang membungkus AutoDock Vina.",
    stages: ["Virtual Screening", "Docking"],
    url: "https://pyrx.sourceforge.io/",
    license: "free",
    tips: "Cocok untuk docking batch skala menengah.",
  },
  {
    name: "GROMACS",
    category: "Molecular Dynamics",
    description: "Paket simulasi dinamika molekuler berkinerja tinggi.",
    stages: ["Molecular Dynamics", "MM/PBSA"],
    url: "https://www.gromacs.org/",
    license: "free",
    tips: "Dokumentasikan force field, model air, ensemble, timestep, dan durasi (ns).",
  },
  {
    name: "AMBER",
    category: "Molecular Dynamics",
    description: "Suite MD dengan AmberTools (gratis) & core berbayar.",
    stages: ["Molecular Dynamics", "MM/PBSA"],
    url: "https://ambermd.org/",
    license: "academic",
    tips: "AmberTools gratis untuk preparasi & analisis; core MD berlisensi.",
  },
  {
    name: "CHARMM-GUI",
    category: "Preparasi",
    description: "Server web untuk membangun sistem simulasi (membran, solvasi).",
    stages: ["Preparasi", "Molecular Dynamics"],
    url: "https://www.charmm-gui.org/",
    license: "free",
    tips: "Simpan input yang dihasilkan sebagai arsip reprodusibilitas.",
  },
  {
    name: "gmx_MMPBSA",
    category: "Free Energy",
    description: "Perhitungan MM/PBSA-GBSA dari lintasan GROMACS.",
    stages: ["MM/PBSA"],
    url: "https://valdes-tresanco-ms.github.io/gmx_MMPBSA/",
    license: "free",
    tips: "Laporkan rentang frame, metode PB/GB, dan dielektrik.",
  },
  {
    name: "PyMOL",
    category: "Visualisasi",
    description: "Visualisasi molekuler untuk pose, interaksi, dan gambar publikasi.",
    stages: ["Analisis", "Visualisasi"],
    url: "https://pymol.org/",
    license: "academic",
    tips: "Tersedia versi open-source; edu-license untuk fitur incentive.",
  },
  {
    name: "VMD",
    category: "Visualisasi",
    description: "Visualisasi & analisis lintasan MD.",
    stages: ["Molecular Dynamics", "Analisis"],
    url: "https://www.ks.uiuc.edu/Research/vmd/",
    license: "academic",
    tips: "Bagus untuk membuat movie lintasan MD.",
  },
  {
    name: "Discovery Studio Visualizer",
    category: "Visualisasi",
    description: "Visualizer gratis untuk analisis interaksi 2D/3D.",
    stages: ["Analisis", "Visualisasi"],
    url: "https://discover.3ds.com/discovery-studio-visualizer-download",
    license: "free",
    tips: "Diagram interaksi 2D-nya sering dipakai di manuskrip.",
  },
  {
    name: "Schrödinger Suite",
    category: "Suite",
    description: "Suite komersial (Glide, Desmond, dll) untuk pemodelan molekuler.",
    stages: ["Docking", "Molecular Dynamics"],
    url: "https://www.schrodinger.com/",
    license: "paid",
    tips: "Tersedia lisensi akademik tertentu; cek ketersediaan kampus.",
  },
  {
    name: "SwissADME",
    category: "ADMET",
    description: "Prediksi drug-likeness & farmakokinetik berbasis web.",
    stages: ["ADMET"],
    url: "http://www.swissadme.ch/",
    license: "free",
    tips: "BOILED-Egg berguna untuk absorpsi GI & BBB.",
  },
  {
    name: "pkCSM",
    category: "ADMET",
    description: "Prediksi properti ADMET berbasis graph-signature.",
    stages: ["ADMET"],
    url: "https://biosig.lab.uq.edu.au/pkcsm/",
    license: "free",
    tips: "Masukkan SMILES kanonik; catat versi & tanggal akses.",
  },
  {
    name: "admetSAR",
    category: "ADMET",
    description: "Prediksi ADMET & toksisitas komprehensif.",
    stages: ["ADMET"],
    url: "http://lmmd.ecust.edu.cn/admetsar2/",
    license: "free",
    tips: "Bandingkan dengan prediktor lain untuk konsistensi.",
  },
  {
    name: "ProTox-II",
    category: "ADMET",
    description: "Prediksi toksisitas oral & endpoint toksikologi.",
    stages: ["ADMET"],
    url: "https://tox-new.charite.de/",
    license: "free",
    tips: "Berguna untuk prediksi LD50 & kelas toksisitas.",
  },
  {
    name: "Cytoscape",
    category: "Network",
    description: "Platform visualisasi & analisis jaringan biologis.",
    stages: ["Network Pharmacology", "Systems Biology"],
    url: "https://cytoscape.org/",
    license: "free",
    tips: "Plugin cytoHubba untuk identifikasi hub gene.",
  },
  {
    name: "STRING",
    category: "Network",
    description: "Database & tool interaksi protein-protein (PPI).",
    stages: ["Network Pharmacology"],
    url: "https://string-db.org/",
    license: "free",
    tips: "Tetapkan confidence score (mis. 0.4/0.7) dan catat.",
  },
  {
    name: "DAVID",
    category: "Enrichment",
    description: "Analisis pengayaan fungsional (GO, KEGG).",
    stages: ["Network Pharmacology", "Omics"],
    url: "https://david.ncifcrf.gov/",
    license: "free",
    tips: "Catat versi database; hasil dapat berubah antar update.",
  },
  {
    name: "Metascape",
    category: "Enrichment",
    description: "Analisis anotasi & pengayaan gen terintegrasi.",
    stages: ["Omics", "Network Pharmacology"],
    url: "https://metascape.org/",
    license: "free",
    tips: "Bagus untuk analisis multi-list gen.",
  },
  {
    name: "SwissTargetPrediction",
    category: "Target Prediction",
    description: "Prediksi target protein untuk molekul kecil.",
    stages: ["Network Pharmacology"],
    url: "http://www.swisstargetprediction.ch/",
    license: "free",
    tips: "Perhatikan spesies (human) & ambang probabilitas.",
  },
  {
    name: "Open Babel",
    category: "Cheminformatics",
    description: "Konversi format kimia & manipulasi molekul.",
    stages: ["Preparasi"],
    url: "https://openbabel.org/",
    license: "free",
    tips: "Gunakan --gen3d untuk membangun koordinat 3D ligan.",
  },
  {
    name: "RDKit",
    category: "Cheminformatics",
    description: "Toolkit cheminformatics untuk deskriptor, fingerprint, filter.",
    stages: ["QSAR", "Virtual Screening", "ADMET"],
    url: "https://www.rdkit.org/",
    license: "free",
    tips: "Ideal untuk pipeline QSAR reprodusibel via Python.",
  },
  {
    name: "PaDEL-Descriptor",
    category: "Cheminformatics",
    description: "Perhitungan deskriptor molekuler & fingerprint.",
    stages: ["QSAR"],
    url: "http://www.yapcwsoft.com/dd/padeldescriptor/",
    license: "free",
    tips: "Catat set deskriptor yang dipilih untuk reprodusibilitas.",
  },
  {
    name: "MODELLER",
    category: "Homology Modeling",
    description: "Pemodelan struktur protein berbasis homologi.",
    stages: ["Homology Modeling"],
    url: "https://salilab.org/modeller/",
    license: "academic",
    tips: "Gratis untuk akademik dengan lisensi; catat template & DOPE score.",
  },
  {
    name: "SWISS-MODEL",
    category: "Homology Modeling",
    description: "Server homology modeling otomatis.",
    stages: ["Homology Modeling"],
    url: "https://swissmodel.expasy.org/",
    license: "free",
    tips: "Perhatikan GMQE/QMEAN untuk kualitas model.",
  },
  {
    name: "BLAST",
    category: "Sequence",
    description: "Pencarian kesamaan sekuens.",
    stages: ["Sequence", "Homology Modeling"],
    url: "https://blast.ncbi.nlm.nih.gov/",
    license: "free",
    tips: "Catat program, E-value cutoff, dan database.",
  },
  {
    name: "Clustal Omega",
    category: "Sequence",
    description: "Multiple sequence alignment.",
    stages: ["Sequence"],
    url: "https://www.ebi.ac.uk/jdispatcher/msa/clustalo",
    license: "free",
    tips: "Simpan file alignment (.aln/.fasta) sebagai lampiran.",
  },
  {
    name: "MEGA",
    category: "Phylogenetics",
    description: "Analisis evolusi & filogenetik molekuler.",
    stages: ["Sequence"],
    url: "https://www.megasoftware.net/",
    license: "free",
    tips: "Laporkan metode pohon, model substitusi, & bootstrap.",
  },
  {
    name: "DESeq2",
    category: "Transcriptomics",
    description: "Analisis ekspresi gen diferensial (R/Bioconductor).",
    stages: ["Omics"],
    url: "https://bioconductor.org/packages/DESeq2/",
    license: "free",
    tips: "Tetapkan ambang log2FC & p-adj serta catat versi paket.",
  },
  {
    name: "clusterProfiler",
    category: "Enrichment",
    description: "Analisis pengayaan fungsional di R.",
    stages: ["Omics"],
    url: "https://bioconductor.org/packages/clusterProfiler/",
    license: "free",
    tips: "Reprodusibel & mendukung GSEA + KEGG/GO.",
  },
  {
    name: "COPASI",
    category: "Systems Biology",
    description: "Simulasi & analisis model biokimia (SBML).",
    stages: ["Systems Biology"],
    url: "https://copasi.org/",
    license: "free",
    tips: "Ekspor model dalam format SBML untuk berbagi.",
  },
  {
    name: "HADDOCK",
    category: "Docking",
    description: "Docking berbasis informasi (protein-protein/peptida).",
    stages: ["Peptide Docking"],
    url: "https://www.bonvinlab.org/software/haddock2.4/",
    license: "academic",
    tips: "Gunakan restraint dari data biokimia bila tersedia.",
  },
  {
    name: "HPEPDOCK",
    category: "Docking",
    description: "Server docking peptida-protein cepat.",
    stages: ["Peptide Docking"],
    url: "http://huanglab.phys.hust.edu.cn/hpepdock/",
    license: "free",
    tips: "Cocok untuk peptida fleksibel; catat model & skor.",
  },
];

export const TOOL_CATEGORIES = Array.from(
  new Set(TOOLS_REGISTRY.map((t) => t.category))
).sort();

export const LICENSE_LABEL: Record<ToolLicense, string> = {
  free: "Gratis",
  academic: "Akademik",
  paid: "Berbayar",
};
