-- =====================================================================
-- InSilico Collab — Seed data (universitas, template metode, registry tool)
-- Jalankan SETELAH 0004_rls.sql. Idempoten (on conflict do update).
-- Dihasilkan otomatis dari src/lib/method-templates.ts & tools-registry.ts
-- =====================================================================

-- Universitas contoh
insert into universities (name, city) values
  ('Universitas Indonesia','Depok'),
  ('Universitas Gadjah Mada','Yogyakarta'),
  ('Institut Teknologi Bandung','Bandung'),
  ('Universitas Airlangga','Surabaya'),
  ('Universitas Padjadjaran','Bandung'),
  ('Universitas Diponegoro','Semarang'),
  ('Universitas Brawijaya','Malang'),
  ('Universitas Hasanuddin','Makassar'),
  ('Universitas Sumatera Utara','Medan'),
  ('IPB University','Bogor')
on conflict (name) do nothing;

-- Template metode in silico
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('molecular_docking', 'Molecular Docking', 'Structure-based', 'Penambatan molekul ligan ke situs aktif reseptor untuk memperkirakan pose & binding affinity.', '[{"name":"Studi Literatur & Target","description":"Identifikasi target protein, situs aktif, dan senyawa uji dari pustaka.","suggested_tools":["PubMed","Google Scholar"],"param_checklist":["Kriteria pemilihan target","Kriteria seleksi senyawa"]},{"name":"Preparasi Reseptor","description":"Ambil struktur dari PDB, hilangkan air/ligan bawaan, tambah hidrogen & muatan.","suggested_tools":["RCSB PDB","AutoDockTools","PyMOL"],"param_checklist":["PDB ID","Resolusi struktur (Å)","Penambahan polar hydrogen","Gasteiger charges"]},{"name":"Preparasi Ligan","description":"Optimasi geometri & konversi format ligan (2D→3D).","suggested_tools":["Open Babel","PubChem","Avogadro"],"param_checklist":["Sumber senyawa (PubChem CID)","Optimasi energi (force field)","Format file (pdbqt)"]},{"name":"Validasi Metode (Redocking)","description":"Redocking ligan kristalografi untuk memvalidasi protokol (RMSD < 2 Å).","suggested_tools":["AutoDock Vina","PyMOL"],"param_checklist":["Nilai RMSD redocking","Ukuran grid box (x,y,z)","Koordinat center grid"]},{"name":"Docking & Skoring","description":"Docking senyawa uji dan pencatatan binding affinity.","suggested_tools":["AutoDock Vina"],"param_checklist":["Exhaustiveness","Jumlah mode","Random seed","Binding affinity (kcal/mol)"]},{"name":"Analisis Interaksi","description":"Analisis ikatan hidrogen, hidrofobik, dan visualisasi pose terbaik.","suggested_tools":["PLIP","Discovery Studio","LigPlot+","PyMOL"],"param_checklist":["Residu interaksi kunci","Tipe interaksi"]},{"name":"Penulisan & Publikasi","description":"Rangkum metode, hasil, dan diskusi menuju manuskrip.","suggested_tools":[],"param_checklist":["Kelengkapan tabel hasil","Kelengkapan gambar interaksi"]}]'::jsonb, ARRAY['AutoDock Vina','PyMOL','Open Babel','Discovery Studio','PLIP']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('virtual_screening', 'Virtual Screening', 'Structure-based', 'Penapisan library senyawa berskala besar untuk menemukan kandidat hit terhadap target.', '[{"name":"Definisi Target & Library","description":"Tentukan target dan kumpulkan library senyawa (database/koleksi).","suggested_tools":["ZINC","PubChem","ChEMBL"],"param_checklist":["Sumber library","Jumlah senyawa awal"]},{"name":"Filter Drug-likeness","description":"Saring dengan aturan Lipinski/Veber sebelum docking.","suggested_tools":["RDKit","SwissADME","DataWarrior"],"param_checklist":["Aturan filter (Lipinski/Veber)","Jumlah lolos filter"]},{"name":"Preparasi Target & Library","description":"Siapkan reseptor & konversi batch ligan.","suggested_tools":["AutoDockTools","Open Babel"],"param_checklist":["Grid box","Protokol preparasi batch"]},{"name":"High-throughput Docking","description":"Docking massal & peringkat berdasarkan skor.","suggested_tools":["PyRx","AutoDock Vina"],"param_checklist":["Exhaustiveness","Cutoff skor","Jumlah kandidat top"]},{"name":"Seleksi Hit & Validasi","description":"Pilih hit teratas, inspeksi pose & interaksi.","suggested_tools":["PLIP","PyMOL"],"param_checklist":["Kriteria seleksi hit","Residu interaksi"]},{"name":"Analisis ADMET Awal","description":"Profil ADMET kandidat terpilih.","suggested_tools":["SwissADME","pkCSM"],"param_checklist":["Parameter ADMET kunci"]},{"name":"Penulisan & Publikasi","description":"Susun laporan penapisan.","suggested_tools":[],"param_checklist":["Kelengkapan pipeline seleksi"]}]'::jsonb, ARRAY['AutoDock Vina','PyRx','Open Babel','RDKit','ZINC','Lipinski filter']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('molecular_dynamics', 'Molecular Dynamics (MD)', 'Simulation', 'Simulasi dinamika atomistik kompleks protein-ligan untuk menilai stabilitas sepanjang waktu.', '[{"name":"Preparasi Sistem","description":"Bangun topologi, solvasi, tambah ion & netralisasi.","suggested_tools":["CHARMM-GUI","GROMACS","AMBER"],"param_checklist":["Force field","Model air","Ukuran box & jenis","Konsentrasi ion"]},{"name":"Minimisasi Energi","description":"Minimisasi untuk menghilangkan clash.","suggested_tools":["GROMACS"],"param_checklist":["Algoritma minimisasi","Jumlah step","Toleransi Fmax"]},{"name":"Ekuilibrasi (NVT/NPT)","description":"Ekuilibrasi suhu & tekanan.","suggested_tools":["GROMACS"],"param_checklist":["Durasi NVT (ps)","Durasi NPT (ps)","Suhu (K)","Tekanan (bar)"]},{"name":"Produksi MD","description":"Jalankan lintasan produksi.","suggested_tools":["GROMACS","AMBER"],"param_checklist":["Durasi simulasi (ns)","Timestep (fs)","Ensemble","Random seed"]},{"name":"Analisis Lintasan","description":"RMSD, RMSF, Rg, SASA, ikatan hidrogen.","suggested_tools":["GROMACS","VMD","MDAnalysis"],"param_checklist":["RMSD rata-rata","RMSF residu kunci","Jumlah H-bond"]},{"name":"Penulisan & Publikasi","description":"Interpretasi stabilitas & manuskrip.","suggested_tools":[],"param_checklist":["Kelengkapan grafik analisis"]}]'::jsonb, ARRAY['GROMACS','AMBER','CHARMM-GUI','VMD','PyMOL']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('mmpbsa_gbsa', 'MM/PBSA-GBSA', 'Simulation', 'Estimasi energi bebas ikatan protein-ligan dari lintasan MD (metode end-point).', '[{"name":"Persiapan Lintasan MD","description":"Gunakan lintasan produksi MD yang stabil.","suggested_tools":["GROMACS","AMBER"],"param_checklist":["Rentang frame yang dipakai","Interval sampling"]},{"name":"Konfigurasi Perhitungan","description":"Atur metode (PB/GB), garam, dan dielektrik.","suggested_tools":["gmx_MMPBSA"],"param_checklist":["Metode (PB/GB)","Konsentrasi garam","Konstanta dielektrik interior/eksterior"]},{"name":"Perhitungan ΔG Binding","description":"Hitung energi bebas ikatan.","suggested_tools":["gmx_MMPBSA","MMPBSA.py"],"param_checklist":["ΔG binding (kcal/mol)","Kontribusi entropi (jika ada)"]},{"name":"Dekomposisi Energi","description":"Dekomposisi per-residu untuk hotspot.","suggested_tools":["gmx_MMPBSA"],"param_checklist":["Residu kontributor utama"]},{"name":"Penulisan & Publikasi","description":"Sintesis hasil energetika.","suggested_tools":[],"param_checklist":["Kelengkapan tabel energi"]}]'::jsonb, ARRAY['gmx_MMPBSA','AMBER (MMPBSA.py)','GROMACS']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('qsar', 'QSAR / QSPR', 'Ligand-based', 'Model hubungan kuantitatif struktur-aktivitas untuk memprediksi aktivitas/properti senyawa.', '[{"name":"Kurasi Dataset","description":"Kumpulkan senyawa + nilai aktivitas, bersihkan duplikat.","suggested_tools":["ChEMBL","PubChem"],"param_checklist":["Ukuran dataset","Satuan aktivitas (IC50/pIC50)","Kriteria kurasi"]},{"name":"Perhitungan Deskriptor/Fingerprint","description":"Hitung deskriptor molekuler.","suggested_tools":["PaDEL-Descriptor","RDKit","Mordred"],"param_checklist":["Jenis deskriptor/fingerprint","Jumlah deskriptor"]},{"name":"Seleksi Fitur & Split Data","description":"Reduksi fitur & pembagian train/test.","suggested_tools":["scikit-learn","R"],"param_checklist":["Metode seleksi fitur","Rasio train/test","Random seed"]},{"name":"Pembangunan Model","description":"Latih model (MLR/PLS/RF/SVM).","suggested_tools":["scikit-learn","Weka","R"],"param_checklist":["Algoritma","Hyperparameter"]},{"name":"Validasi Model","description":"Validasi internal & eksternal, applicability domain.","suggested_tools":["scikit-learn"],"param_checklist":["R²","Q²","RMSE","Applicability domain"]},{"name":"Penulisan & Publikasi","description":"Laporkan model & prediksi.","suggested_tools":[],"param_checklist":["Kelengkapan metrik validasi"]}]'::jsonb, ARRAY['RDKit','PaDEL-Descriptor','R','scikit-learn','DataWarrior','Weka']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('pharmacophore', 'Pharmacophore Modeling', 'Ligand-based', 'Pemodelan fitur farmakofor (donor/akseptor/hidrofobik) untuk penapisan berbasis fitur.', '[{"name":"Kumpulkan Ligan Aktif","description":"Set ligan aktif (dan inaktif) sebagai basis model.","suggested_tools":["ChEMBL"],"param_checklist":["Jumlah ligan aktif/inaktif"]},{"name":"Bangun Model Farmakofor","description":"Turunkan fitur farmakofor dari ligan/kompleks.","suggested_tools":["PharmaGist","LigandScout"],"param_checklist":["Jumlah fitur","Jenis fitur","Toleransi"]},{"name":"Validasi Model","description":"Uji dengan set decoy (ROC/EF).","suggested_tools":["Pharmit"],"param_checklist":["AUC ROC","Enrichment factor"]},{"name":"Screening Berbasis Farmakofor","description":"Penapisan library dengan model.","suggested_tools":["Pharmit"],"param_checklist":["Ukuran library","Kriteria hit"]},{"name":"Penulisan & Publikasi","description":"Rangkum model & hasil penapisan.","suggested_tools":[],"param_checklist":["Kelengkapan validasi"]}]'::jsonb, ARRAY['LigandScout','Pharmit','PharmaGist','RDKit']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('admet', 'ADMET / Drug-likeness', 'Ligand-based', 'Prediksi absorpsi, distribusi, metabolisme, ekskresi, toksisitas & kemiripan obat.', '[{"name":"Kurasi Senyawa","description":"Siapkan daftar senyawa (SMILES).","suggested_tools":["PubChem"],"param_checklist":["Jumlah senyawa","Sumber SMILES"]},{"name":"Drug-likeness","description":"Evaluasi Lipinski, Veber, Egan.","suggested_tools":["SwissADME"],"param_checklist":["Aturan yang dipakai","Jumlah pelanggaran"]},{"name":"Prediksi Farmakokinetik","description":"Absorpsi, BBB, CYP, klirens.","suggested_tools":["pkCSM","admetSAR"],"param_checklist":["Parameter PK kunci"]},{"name":"Prediksi Toksisitas","description":"Hepatotoksisitas, mutagenisitas, LD50.","suggested_tools":["ProTox-II","admetSAR"],"param_checklist":["Endpoint toksisitas","Kelas toksisitas"]},{"name":"Penulisan & Publikasi","description":"Tabulasi profil ADMET.","suggested_tools":[],"param_checklist":["Kelengkapan tabel ADMET"]}]'::jsonb, ARRAY['SwissADME','pkCSM','admetSAR','ProTox-II']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('network_pharmacology', 'Network Pharmacology', 'Systems', 'Pendekatan sistem: senyawa → target → jalur, cocok untuk bahan alam/jamu multi-komponen.', '[{"name":"Koleksi Senyawa Aktif","description":"Kumpulkan senyawa bahan alam & skrining oral bioavailability.","suggested_tools":["TCMSP","PubChem"],"param_checklist":["Sumber senyawa","Kriteria OB/DL"]},{"name":"Prediksi Target Senyawa","description":"Prediksi target protein tiap senyawa.","suggested_tools":["SwissTargetPrediction","TargetNet"],"param_checklist":["Ambang probabilitas target"]},{"name":"Target Penyakit","description":"Kumpulkan target terkait penyakit.","suggested_tools":["GeneCards","OMIM","DisGeNET"],"param_checklist":["Kata kunci penyakit","Ambang skor relevansi"]},{"name":"Irisan & PPI Network","description":"Irisan target senyawa-penyakit → jaringan PPI.","suggested_tools":["STRING","Venn","Cytoscape"],"param_checklist":["Confidence score STRING","Jumlah node irisan"]},{"name":"Analisis Jaringan & Hub","description":"Analisis topologi & pemilihan hub gene.","suggested_tools":["Cytoscape","cytoHubba"],"param_checklist":["Metrik topologi (degree/betweenness)","Jumlah hub"]},{"name":"Enrichment GO & KEGG","description":"Analisis pengayaan fungsi & jalur.","suggested_tools":["DAVID","KEGG","Metascape"],"param_checklist":["Ambang p-value/FDR","Jalur signifikan teratas"]},{"name":"Docking Validasi","description":"Validasi ikatan hub gene–senyawa kunci.","suggested_tools":["AutoDock Vina","PyMOL"],"param_checklist":["Grid box","Binding affinity"]},{"name":"Penulisan & Publikasi","description":"Sintesis mekanisme & manuskrip.","suggested_tools":[],"param_checklist":["Kelengkapan gambar jaringan"]}]'::jsonb, ARRAY['SwissTargetPrediction','STRING','Cytoscape','DAVID','KEGG','GeneCards']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('homology_modeling', 'Homology Modeling', 'Structure-based', 'Prediksi struktur 3D protein berbasis template ketika struktur eksperimental tidak tersedia.', '[{"name":"Ambil Sekuens Target","description":"Dapatkan sekuens protein target.","suggested_tools":["UniProt","NCBI"],"param_checklist":["UniProt ID","Panjang sekuens"]},{"name":"Pencarian & Seleksi Template","description":"Cari template homolog (identitas memadai).","suggested_tools":["BLAST","HHpred"],"param_checklist":["Template PDB ID","% identitas sekuens","Coverage"]},{"name":"Alignment & Pembangunan Model","description":"Alignment & bangun model 3D.","suggested_tools":["MODELLER","SWISS-MODEL"],"param_checklist":["Metode alignment","Jumlah model dihasilkan"]},{"name":"Refinement & Validasi","description":"Loop refinement & validasi Ramachandran.","suggested_tools":["PROCHECK","MolProbity","ProSA"],"param_checklist":["% residu favored region","Skor QMEAN/DOPE"]},{"name":"Penulisan & Publikasi","description":"Dokumentasi model.","suggested_tools":[],"param_checklist":["Kelengkapan Ramachandran plot"]}]'::jsonb, ARRAY['MODELLER','SWISS-MODEL','PROCHECK','MolProbity','PyMOL']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('bioinformatics_seq', 'Bioinformatics (Sequence/BLAST)', 'Sequence', 'Analisis sekuens: pencarian homolog, alignment berganda, dan filogenetika.', '[{"name":"Pengumpulan Sekuens","description":"Kumpulkan sekuens dari database.","suggested_tools":["NCBI","UniProt"],"param_checklist":["Jumlah sekuens","Kriteria pemilihan"]},{"name":"Pencarian Homolog (BLAST)","description":"Cari sekuens serupa.","suggested_tools":["BLAST"],"param_checklist":["Program BLAST","E-value cutoff","% identitas"]},{"name":"Multiple Sequence Alignment","description":"Alignment berganda.","suggested_tools":["Clustal Omega","MAFFT"],"param_checklist":["Algoritma alignment","Parameter gap"]},{"name":"Analisis Filogenetik","description":"Bangun pohon filogenetik.","suggested_tools":["MEGA","IQ-TREE"],"param_checklist":["Metode (NJ/ML)","Bootstrap","Model substitusi"]},{"name":"Penulisan & Publikasi","description":"Interpretasi konservasi/filogeni.","suggested_tools":[],"param_checklist":["Kelengkapan pohon & alignment"]}]'::jsonb, ARRAY['BLAST','Clustal Omega','MEGA','MAFFT','Jalview']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('genomics_transcriptomics', 'Genomics / Transcriptomics (DEG)', 'Omics', 'Analisis ekspresi gen diferensial (DEG) dan pengayaan jalur dari data RNA-seq/microarray.', '[{"name":"Akuisisi Data","description":"Unduh dataset ekspresi & metadata.","suggested_tools":["GEO","ArrayExpress","TCGA"],"param_checklist":["Accession dataset (GSE)","Jumlah sampel/grup"]},{"name":"Pra-pemrosesan & QC","description":"Normalisasi & kontrol kualitas.","suggested_tools":["R","FastQC"],"param_checklist":["Metode normalisasi","Kriteria QC"]},{"name":"Analisis DEG","description":"Identifikasi gen diferensial.","suggested_tools":["DESeq2","limma","edgeR"],"param_checklist":["Ambang log2FC","Ambang p-adj/FDR","Jumlah DEG"]},{"name":"Enrichment & Pathway","description":"GO/KEGG/GSEA pada DEG.","suggested_tools":["clusterProfiler","Enrichr","GSEA"],"param_checklist":["Ambang signifikansi","Jalur teratas"]},{"name":"Visualisasi","description":"Volcano, heatmap, PCA.","suggested_tools":["R (ggplot2)","pheatmap"],"param_checklist":["Kelengkapan plot"]},{"name":"Penulisan & Publikasi","description":"Sintesis temuan ekspresi.","suggested_tools":[],"param_checklist":["Kelengkapan tabel DEG"]}]'::jsonb, ARRAY['GEO','R (DESeq2/limma)','edgeR','clusterProfiler','GSEA','Enrichr']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('systems_biology', 'Systems Biology', 'Systems', 'Pemodelan jaringan biologis & simulasi dinamika sistem (jalur metabolik/regulasi).', '[{"name":"Rekonstruksi Jaringan","description":"Bangun model jaringan/jalur.","suggested_tools":["CellDesigner","Cytoscape"],"param_checklist":["Sumber interaksi","Jumlah komponen"]},{"name":"Parameterisasi Model","description":"Tetapkan laju & kondisi awal.","suggested_tools":["COPASI"],"param_checklist":["Sumber parameter kinetik","Kondisi awal"]},{"name":"Simulasi & Analisis","description":"Simulasi dinamika & analisis sensitivitas.","suggested_tools":["COPASI"],"param_checklist":["Jenis simulasi","Durasi","Parameter sensitif"]},{"name":"Validasi","description":"Bandingkan dengan data eksperimen.","suggested_tools":[],"param_checklist":["Kriteria validasi"]},{"name":"Penulisan & Publikasi","description":"Dokumentasi model (SBML).","suggested_tools":["SBML"],"param_checklist":["Ketersediaan model SBML"]}]'::jsonb, ARRAY['Cytoscape','COPASI','CellDesigner','SBML']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('peptide_docking', 'Molecular Docking Peptida', 'Structure-based', 'Docking ligan peptida ke reseptor dengan mempertimbangkan fleksibilitas peptida.', '[{"name":"Preparasi Reseptor & Peptida","description":"Siapkan reseptor & struktur peptida.","suggested_tools":["PyMOL","PEP-FOLD"],"param_checklist":["Sumber struktur peptida","Protokol preparasi"]},{"name":"Prediksi/Docking Peptida","description":"Docking peptida-protein.","suggested_tools":["HPEPDOCK","GalaxyPepDock","HADDOCK"],"param_checklist":["Server/metode","Jumlah model","Skor docking"]},{"name":"Seleksi & Refinement","description":"Pilih model & refine antarmuka.","suggested_tools":["HADDOCK","FlexPepDock"],"param_checklist":["Kriteria seleksi model"]},{"name":"Analisis Interaksi","description":"Analisis antarmuka & ikatan.","suggested_tools":["PLIP","PyMOL"],"param_checklist":["Residu antarmuka kunci"]},{"name":"Penulisan & Publikasi","description":"Rangkum hasil.","suggested_tools":[],"param_checklist":["Kelengkapan analisis antarmuka"]}]'::jsonb, ARRAY['HPEPDOCK','HADDOCK','GalaxyPepDock','PyMOL']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('drug_repurposing', 'Drug Repurposing', 'Ligand-based', 'Penemuan indikasi baru untuk obat yang sudah ada melalui pendekatan in silico.', '[{"name":"Koleksi Obat Terdaftar","description":"Kumpulkan obat approved sebagai kandidat.","suggested_tools":["DrugBank","ZINC"],"param_checklist":["Sumber daftar obat","Jumlah kandidat"]},{"name":"Identifikasi Target Penyakit","description":"Tentukan target/biomarker penyakit.","suggested_tools":["GeneCards","DisGeNET"],"param_checklist":["Target utama"]},{"name":"Screening/Docking Ulang","description":"Docking obat terhadap target baru.","suggested_tools":["AutoDock Vina","PyRx"],"param_checklist":["Grid box","Cutoff skor"]},{"name":"Analisis Jaringan Obat-Target","description":"Bangun jaringan obat-target-penyakit.","suggested_tools":["Cytoscape","STRING"],"param_checklist":["Metrik jaringan"]},{"name":"Prioritasi Kandidat","description":"Peringkat kandidat repurposing.","suggested_tools":[],"param_checklist":["Kriteria prioritas"]},{"name":"Penulisan & Publikasi","description":"Susun laporan.","suggested_tools":[],"param_checklist":["Kelengkapan rasionalisasi"]}]'::jsonb, ARRAY['DrugBank','AutoDock Vina','SwissTargetPrediction','STRING','Connectivity Map']::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;
insert into method_templates (key, name, category, description, default_stages, suggested_tools) values ('custom', 'Custom / From Scratch', 'Custom', 'Mulai dari nol dan susun tahapan pipeline sesuai kebutuhan tim.', '[{"name":"Perencanaan","description":"Definisikan tujuan, pertanyaan penelitian, dan alur kerja.","suggested_tools":[],"param_checklist":["Tujuan penelitian","Definisi keluaran"]},{"name":"Pelaksanaan","description":"Kerjakan analisis inti.","suggested_tools":[],"param_checklist":[]},{"name":"Analisis Hasil","description":"Interpretasi & visualisasi hasil.","suggested_tools":[],"param_checklist":[]},{"name":"Penulisan & Publikasi","description":"Susun manuskrip.","suggested_tools":[],"param_checklist":[]}]'::jsonb, ARRAY[]::text[])
on conflict (key) do update set name=excluded.name, category=excluded.category, description=excluded.description, default_stages=excluded.default_stages, suggested_tools=excluded.suggested_tools;

-- Registry tool in silico
insert into tools (name, category, description, stages, url, license, tips) values ('AutoDock Vina', 'Docking', 'Program docking molekuler open-source yang cepat dan populer.', ARRAY['Docking','Virtual Screening','Validasi']::text[], 'https://vina.scripps.edu/', 'free', 'Validasi protokol dengan redocking (RMSD < 2 Å) sebelum docking senyawa uji. Catat exhaustiveness & seed.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('AutoDockTools (MGLTools)', 'Preparasi', 'GUI untuk preparasi reseptor/ligan & pembuatan grid box.', ARRAY['Preparasi']::text[], 'https://ccsb.scripps.edu/mgltools/', 'free', 'Simpan koordinat & ukuran grid box agar reprodusibel.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('PyRx', 'Docking', 'Antarmuka virtual screening yang membungkus AutoDock Vina.', ARRAY['Virtual Screening','Docking']::text[], 'https://pyrx.sourceforge.io/', 'free', 'Cocok untuk docking batch skala menengah.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('GROMACS', 'Molecular Dynamics', 'Paket simulasi dinamika molekuler berkinerja tinggi.', ARRAY['Molecular Dynamics','MM/PBSA']::text[], 'https://www.gromacs.org/', 'free', 'Dokumentasikan force field, model air, ensemble, timestep, dan durasi (ns).')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('AMBER', 'Molecular Dynamics', 'Suite MD dengan AmberTools (gratis) & core berbayar.', ARRAY['Molecular Dynamics','MM/PBSA']::text[], 'https://ambermd.org/', 'academic', 'AmberTools gratis untuk preparasi & analisis; core MD berlisensi.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('CHARMM-GUI', 'Preparasi', 'Server web untuk membangun sistem simulasi (membran, solvasi).', ARRAY['Preparasi','Molecular Dynamics']::text[], 'https://www.charmm-gui.org/', 'free', 'Simpan input yang dihasilkan sebagai arsip reprodusibilitas.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('gmx_MMPBSA', 'Free Energy', 'Perhitungan MM/PBSA-GBSA dari lintasan GROMACS.', ARRAY['MM/PBSA']::text[], 'https://valdes-tresanco-ms.github.io/gmx_MMPBSA/', 'free', 'Laporkan rentang frame, metode PB/GB, dan dielektrik.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('PyMOL', 'Visualisasi', 'Visualisasi molekuler untuk pose, interaksi, dan gambar publikasi.', ARRAY['Analisis','Visualisasi']::text[], 'https://pymol.org/', 'academic', 'Tersedia versi open-source; edu-license untuk fitur incentive.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('VMD', 'Visualisasi', 'Visualisasi & analisis lintasan MD.', ARRAY['Molecular Dynamics','Analisis']::text[], 'https://www.ks.uiuc.edu/Research/vmd/', 'academic', 'Bagus untuk membuat movie lintasan MD.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('Discovery Studio Visualizer', 'Visualisasi', 'Visualizer gratis untuk analisis interaksi 2D/3D.', ARRAY['Analisis','Visualisasi']::text[], 'https://discover.3ds.com/discovery-studio-visualizer-download', 'free', 'Diagram interaksi 2D-nya sering dipakai di manuskrip.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('Schrödinger Suite', 'Suite', 'Suite komersial (Glide, Desmond, dll) untuk pemodelan molekuler.', ARRAY['Docking','Molecular Dynamics']::text[], 'https://www.schrodinger.com/', 'paid', 'Tersedia lisensi akademik tertentu; cek ketersediaan kampus.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('SwissADME', 'ADMET', 'Prediksi drug-likeness & farmakokinetik berbasis web.', ARRAY['ADMET']::text[], 'http://www.swissadme.ch/', 'free', 'BOILED-Egg berguna untuk absorpsi GI & BBB.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('pkCSM', 'ADMET', 'Prediksi properti ADMET berbasis graph-signature.', ARRAY['ADMET']::text[], 'https://biosig.lab.uq.edu.au/pkcsm/', 'free', 'Masukkan SMILES kanonik; catat versi & tanggal akses.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('admetSAR', 'ADMET', 'Prediksi ADMET & toksisitas komprehensif.', ARRAY['ADMET']::text[], 'http://lmmd.ecust.edu.cn/admetsar2/', 'free', 'Bandingkan dengan prediktor lain untuk konsistensi.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('ProTox-II', 'ADMET', 'Prediksi toksisitas oral & endpoint toksikologi.', ARRAY['ADMET']::text[], 'https://tox-new.charite.de/', 'free', 'Berguna untuk prediksi LD50 & kelas toksisitas.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('Cytoscape', 'Network', 'Platform visualisasi & analisis jaringan biologis.', ARRAY['Network Pharmacology','Systems Biology']::text[], 'https://cytoscape.org/', 'free', 'Plugin cytoHubba untuk identifikasi hub gene.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('STRING', 'Network', 'Database & tool interaksi protein-protein (PPI).', ARRAY['Network Pharmacology']::text[], 'https://string-db.org/', 'free', 'Tetapkan confidence score (mis. 0.4/0.7) dan catat.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('DAVID', 'Enrichment', 'Analisis pengayaan fungsional (GO, KEGG).', ARRAY['Network Pharmacology','Omics']::text[], 'https://david.ncifcrf.gov/', 'free', 'Catat versi database; hasil dapat berubah antar update.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('Metascape', 'Enrichment', 'Analisis anotasi & pengayaan gen terintegrasi.', ARRAY['Omics','Network Pharmacology']::text[], 'https://metascape.org/', 'free', 'Bagus untuk analisis multi-list gen.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('SwissTargetPrediction', 'Target Prediction', 'Prediksi target protein untuk molekul kecil.', ARRAY['Network Pharmacology']::text[], 'http://www.swisstargetprediction.ch/', 'free', 'Perhatikan spesies (human) & ambang probabilitas.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('Open Babel', 'Cheminformatics', 'Konversi format kimia & manipulasi molekul.', ARRAY['Preparasi']::text[], 'https://openbabel.org/', 'free', 'Gunakan --gen3d untuk membangun koordinat 3D ligan.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('RDKit', 'Cheminformatics', 'Toolkit cheminformatics untuk deskriptor, fingerprint, filter.', ARRAY['QSAR','Virtual Screening','ADMET']::text[], 'https://www.rdkit.org/', 'free', 'Ideal untuk pipeline QSAR reprodusibel via Python.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('PaDEL-Descriptor', 'Cheminformatics', 'Perhitungan deskriptor molekuler & fingerprint.', ARRAY['QSAR']::text[], 'http://www.yapcwsoft.com/dd/padeldescriptor/', 'free', 'Catat set deskriptor yang dipilih untuk reprodusibilitas.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('MODELLER', 'Homology Modeling', 'Pemodelan struktur protein berbasis homologi.', ARRAY['Homology Modeling']::text[], 'https://salilab.org/modeller/', 'academic', 'Gratis untuk akademik dengan lisensi; catat template & DOPE score.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('SWISS-MODEL', 'Homology Modeling', 'Server homology modeling otomatis.', ARRAY['Homology Modeling']::text[], 'https://swissmodel.expasy.org/', 'free', 'Perhatikan GMQE/QMEAN untuk kualitas model.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('BLAST', 'Sequence', 'Pencarian kesamaan sekuens.', ARRAY['Sequence','Homology Modeling']::text[], 'https://blast.ncbi.nlm.nih.gov/', 'free', 'Catat program, E-value cutoff, dan database.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('Clustal Omega', 'Sequence', 'Multiple sequence alignment.', ARRAY['Sequence']::text[], 'https://www.ebi.ac.uk/jdispatcher/msa/clustalo', 'free', 'Simpan file alignment (.aln/.fasta) sebagai lampiran.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('MEGA', 'Phylogenetics', 'Analisis evolusi & filogenetik molekuler.', ARRAY['Sequence']::text[], 'https://www.megasoftware.net/', 'free', 'Laporkan metode pohon, model substitusi, & bootstrap.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('DESeq2', 'Transcriptomics', 'Analisis ekspresi gen diferensial (R/Bioconductor).', ARRAY['Omics']::text[], 'https://bioconductor.org/packages/DESeq2/', 'free', 'Tetapkan ambang log2FC & p-adj serta catat versi paket.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('clusterProfiler', 'Enrichment', 'Analisis pengayaan fungsional di R.', ARRAY['Omics']::text[], 'https://bioconductor.org/packages/clusterProfiler/', 'free', 'Reprodusibel & mendukung GSEA + KEGG/GO.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('COPASI', 'Systems Biology', 'Simulasi & analisis model biokimia (SBML).', ARRAY['Systems Biology']::text[], 'https://copasi.org/', 'free', 'Ekspor model dalam format SBML untuk berbagi.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('HADDOCK', 'Docking', 'Docking berbasis informasi (protein-protein/peptida).', ARRAY['Peptide Docking']::text[], 'https://www.bonvinlab.org/software/haddock2.4/', 'academic', 'Gunakan restraint dari data biokimia bila tersedia.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
insert into tools (name, category, description, stages, url, license, tips) values ('HPEPDOCK', 'Docking', 'Server docking peptida-protein cepat.', ARRAY['Peptide Docking']::text[], 'http://huanglab.phys.hust.edu.cn/hpepdock/', 'free', 'Cocok untuk peptida fleksibel; catat model & skor.')
on conflict (name) do update set category=excluded.category, description=excluded.description, stages=excluded.stages, url=excluded.url, license=excluded.license, tips=excluded.tips;
