-- =====================================================================
-- SiliCollab, daftar universitas Indonesia yang lengkap
-- Jalankan di SQL Editor Supabase. Idempoten (on conflict do nothing),
-- jadi aman dijalankan berkali-kali tanpa menggandakan data.
-- Mencakup PTN besar (umum, keguruan, UIN, UPN, institut teknologi)
-- dan PTS besar yang punya fakultas kedokteran / farmasi / biologi.
-- =====================================================================

insert into universities (name, city) values
  -- PTN papan atas
  ('Universitas Indonesia', 'Depok'),
  ('Universitas Gadjah Mada', 'Yogyakarta'),
  ('Institut Teknologi Bandung', 'Bandung'),
  ('IPB University', 'Bogor'),
  ('Institut Teknologi Sepuluh Nopember', 'Surabaya'),
  ('Universitas Airlangga', 'Surabaya'),
  ('Universitas Padjadjaran', 'Bandung'),
  ('Universitas Diponegoro', 'Semarang'),
  ('Universitas Brawijaya', 'Malang'),
  ('Universitas Sebelas Maret', 'Surakarta'),
  ('Universitas Hasanuddin', 'Makassar'),
  ('Universitas Sumatera Utara', 'Medan'),
  ('Universitas Andalas', 'Padang'),
  ('Universitas Sriwijaya', 'Palembang'),
  ('Universitas Jenderal Soedirman', 'Purwokerto'),
  ('Universitas Jember', 'Jember'),
  ('Universitas Lampung', 'Bandar Lampung'),
  ('Universitas Riau', 'Pekanbaru'),
  ('Universitas Jambi', 'Jambi'),
  ('Universitas Bengkulu', 'Bengkulu'),
  ('Universitas Tanjungpura', 'Pontianak'),
  ('Universitas Mulawarman', 'Samarinda'),
  ('Universitas Lambung Mangkurat', 'Banjarmasin'),
  ('Universitas Palangka Raya', 'Palangka Raya'),
  ('Universitas Syiah Kuala', 'Banda Aceh'),
  ('Universitas Malikussaleh', 'Lhokseumawe'),
  ('Universitas Udayana', 'Denpasar'),
  ('Universitas Mataram', 'Mataram'),
  ('Universitas Nusa Cendana', 'Kupang'),
  ('Universitas Sam Ratulangi', 'Manado'),
  ('Universitas Tadulako', 'Palu'),
  ('Universitas Halu Oleo', 'Kendari'),
  ('Universitas Cenderawasih', 'Jayapura'),
  ('Universitas Pattimura', 'Ambon'),
  ('Universitas Khairun', 'Ternate'),
  ('Universitas Papua', 'Manokwari'),
  ('Universitas Trunojoyo Madura', 'Bangkalan'),
  ('Universitas Tidar', 'Magelang'),
  ('Universitas Singaperbangsa Karawang', 'Karawang'),
  ('Universitas Siliwangi', 'Tasikmalaya'),
  ('Universitas Sultan Ageng Tirtayasa', 'Serang'),
  ('Universitas Bangka Belitung', 'Pangkalpinang'),
  ('Universitas Maritim Raja Ali Haji', 'Tanjungpinang'),
  ('Universitas Borneo Tarakan', 'Tarakan'),
  ('Universitas Sulawesi Barat', 'Majene'),
  ('Universitas Timor', 'Kefamenanu'),
  ('Universitas Musamus', 'Merauke'),
  ('Institut Teknologi Sumatera', 'Lampung Selatan'),
  ('Institut Teknologi Kalimantan', 'Balikpapan'),
  -- Universitas Negeri (eks IKIP)
  ('Universitas Pendidikan Indonesia', 'Bandung'),
  ('Universitas Negeri Jakarta', 'Jakarta'),
  ('Universitas Negeri Yogyakarta', 'Yogyakarta'),
  ('Universitas Negeri Surabaya', 'Surabaya'),
  ('Universitas Negeri Semarang', 'Semarang'),
  ('Universitas Negeri Malang', 'Malang'),
  ('Universitas Negeri Medan', 'Medan'),
  ('Universitas Negeri Padang', 'Padang'),
  ('Universitas Negeri Makassar', 'Makassar'),
  ('Universitas Negeri Manado', 'Manado'),
  ('Universitas Negeri Gorontalo', 'Gorontalo'),
  ('Universitas Negeri Padjadjaran', 'Bandung'),
  -- UPN Veteran
  ('UPN Veteran Jakarta', 'Jakarta'),
  ('UPN Veteran Yogyakarta', 'Yogyakarta'),
  ('UPN Veteran Jawa Timur', 'Surabaya'),
  ('Universitas Terbuka', 'Tangerang Selatan'),
  -- UIN dengan fakultas kesehatan / sains
  ('UIN Syarif Hidayatullah Jakarta', 'Jakarta'),
  ('UIN Maulana Malik Ibrahim Malang', 'Malang'),
  ('UIN Sunan Kalijaga', 'Yogyakarta'),
  ('UIN Sunan Gunung Djati', 'Bandung'),
  ('UIN Alauddin Makassar', 'Makassar'),
  ('UIN Walisongo', 'Semarang'),
  -- PTS besar (kedokteran / farmasi / biologi)
  ('Universitas Bina Nusantara', 'Jakarta'),
  ('Universitas Trisakti', 'Jakarta'),
  ('Universitas Katolik Indonesia Atma Jaya', 'Jakarta'),
  ('Universitas Tarumanagara', 'Jakarta'),
  ('Universitas Pelita Harapan', 'Tangerang'),
  ('Universitas YARSI', 'Jakarta'),
  ('Universitas Pancasila', 'Jakarta'),
  ('Universitas Kristen Krida Wacana', 'Jakarta'),
  ('Universitas Muhammadiyah Prof. Dr. Hamka', 'Jakarta'),
  ('Universitas Esa Unggul', 'Jakarta'),
  ('Universitas Mercu Buana', 'Jakarta'),
  ('Universitas Gunadarma', 'Depok'),
  ('Universitas Muhammadiyah Yogyakarta', 'Yogyakarta'),
  ('Universitas Islam Indonesia', 'Yogyakarta'),
  ('Universitas Ahmad Dahlan', 'Yogyakarta'),
  ('Universitas Sanata Dharma', 'Yogyakarta'),
  ('Universitas Atma Jaya Yogyakarta', 'Yogyakarta'),
  ('Universitas Muhammadiyah Surakarta', 'Surakarta'),
  ('Universitas Muhammadiyah Malang', 'Malang'),
  ('Universitas Surabaya', 'Surabaya'),
  ('Universitas Kristen Petra', 'Surabaya'),
  ('Universitas Katolik Widya Mandala Surabaya', 'Surabaya'),
  ('Universitas Hang Tuah', 'Surabaya'),
  ('Universitas Katolik Parahyangan', 'Bandung'),
  ('Universitas Kristen Maranatha', 'Bandung'),
  ('Universitas Islam Bandung', 'Bandung'),
  ('Universitas Jenderal Achmad Yani', 'Cimahi'),
  ('Universitas Katolik Soegijapranata', 'Semarang'),
  ('Universitas Islam Sultan Agung', 'Semarang'),
  ('Universitas Dian Nuswantoro', 'Semarang'),
  ('Universitas Muslim Indonesia', 'Makassar'),
  ('Universitas Prima Indonesia', 'Medan'),
  ('Universitas Katolik Musi Charitas', 'Palembang')
on conflict (name) do nothing;
